version: "3.9"

services:
  postgres:
    build: ./postgres     # Eğer postgres reposunda Dockerfile varsa
    container_name: cve_postgres
    environment:
      POSTGRES_USER: ost
      POSTGRES_PASSWORD: CvE1324
      POSTGRES_DB: cvebos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cve_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://ost:CvE1324@postgres:5432/cvebos
    ports:
      - "8000:8000"

  scanner:
    build: ./scanner
    container_name: cve_scanner
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: cve_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
